uek_demo_homepage:
    path:     /
    defaults: { _controller: UekDemoBundle:Default:index }

uek_demo_recenzja_index:
    path:     /recenzja/index
    defaults:
        _controller: UekDemoBundle:Recenzja:index

uek_demo_filmy_index:
    path:     /filmy/index
    defaults:
        _controller: UekDemoBundle:Filmy:index

uek_demo_gatunki_index:
    path:     /gatunki/index
    defaults:
        _controller: UekDemoBundle:Gatunki:index