uek_demo_homepage:
    path:     /
    defaults: { _controller: UekDemoBundle:Default:index }

uek_demo_recenzja_index:
    path:     /recenzja/index
    defaults:
        _controller: UekDemoBundle:Recenzja:index

uek_demo_recenzja_create:
    path:     /recenzja/create
    defaults:
        _controller: UekDemoBundle:Recenzja:create

uek_demo_filmy_index:
    path:     /filmy/index
    defaults:
        _controller: UekDemoBundle:Filmy:index

uek_demo_filmy_show:
    path:     /filmy/show/{gatunek}
    defaults:
        _controller: UekDemoBundle:Filmy:show	

uek_demo_gatunki_index:
    path:     /gatunki/index
    defaults:
        _controller: UekDemoBundle:Gatunki:index

uek_demo_wypozyczenia_index:
    path:     /wypozyczenia/index
    defaults:
        _controller: UekDemoBundle:Wypozyczenia:index

uek_demo_recenzjaNajwiecej_index:
    path:     /najczesciejRecenzje/index
    defaults:
        _controller: UekDemoBundle:NajczesciejRecenzje:index

uek_demo_popularneFilmy_index:
    path:     /popularneFilmy/index
    defaults:
        _controller: UekDemoBundle:PopularneFilmy:index
